excerpt_separator: ""
highlighter : pygments
markdown: kramdown
url: http://rhlKumar.github.io
title: A blog
email: rahulkumar.iitb@gmail.com
author: Rahul Kumar
description: My awesome new site
paginate: 1
google_analytics: UA-65878362-1 
